version: '3.8'

services:
  app:
    container_name: drf_app
    build: ./app
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python3 manage.py makemigrations --noinput &&
             while ! python3 manage.py migrate --noinput ; do sleep 1 ; done && 
             python3 manage.py collectstatic --noinput &&
             python3 manage.py createsuperuser --user admin --noinput --email admin@admin.com --noinput ;
             python3 manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=postgresqlpassword
  db:
    container_name: drf_db
    image: postgres:latest
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgresqlpassword
  redis:
    container_name: drf_redis
    image: redis:latest
    ports:
      - 6379:6379
  celery:
    container_name: drf_celery
    restart: always
    build: ./app
    command: >
      sh -c "celery -A app worker -l INFO"
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=postgresqlpassword
  celery_beat:
    container_name: drf_celery_beat
    restart: always
    build: ./app
    command: >
      sh -c "celery -A app beat -l INFO"
    volumes:
      - ./app:/app
    depends_on:
      - db
      - redis
      - celery