# Generated by Django 4.1 on 2022-08-25 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_name', models.CharField(max_length=120, null=True, verbose_name='Coin Name')),
                ('coin_price_source', models.CharField(max_length=120, null=True, verbose_name='Coin Price Source')),
                ('coin_price', models.PositiveIntegerField(verbose_name='Coin Price')),
                ('coin_date_added', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
