# Generated by Django 4.1 on 2022-08-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_crypto_coin_date_changed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto',
            name='coin_date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='coin_date_changed',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
